In [2]:
import pandas as pd

df = pd.read_csv("custom.csv")

In [3]:
import numpy as np

In [4]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [5]:
#checking null values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [8]:
#converting all columns string as snack case and also removing special characters.
df.columns = df.columns.str.lower()

In [9]:
df.columns = df.columns.str.replace(" " , "_")

In [10]:
df = df.rename(columns = {'purchase_amount_(usd)' : "purchase_amount_usd"})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [13]:
#Here values of 'subscription_status' ,'promo_code_used' and 'discount_applied' are looks same, so let's check 
(df["subscription_status"] == df["discount_applied"]).all()

np.False_

In [14]:
(df["promo_code_used"] == df["discount_applied"]).all()

np.True_

In [15]:
#But only 'promo_code_used' and 'discount_applied' are same ,so I'll remove any one like 'promo_code_used'.
df = df.drop(('promo_code_used'),axis = 1)

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [17]:
#Creating a column "age_group" to group as per age .
labels = ['Young_Adult','Adult','Middle_aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4 , labels = labels)

In [18]:
df["age_group"].head(10)

0    Middle_aged
1    Young_Adult
2    Middle_aged
3    Young_Adult
4    Middle_aged
5    Middle_aged
6         Senior
7    Young_Adult
8    Young_Adult
9    Middle_aged
Name: age_group, dtype: category
Categories (4, object): ['Young_Adult' < 'Adult' < 'Middle_aged' < 'Senior']

In [19]:
df["age_group"].astype(object)

0       Middle_aged
1       Young_Adult
2       Middle_aged
3       Young_Adult
4       Middle_aged
           ...
3895          Adult
3896    Middle_aged
3897    Middle_aged
3898          Adult
3899    Middle_aged
Name: age_group, Length: 3900, dtype: object

In [20]:
#Checking Data type of each columns.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_usd     3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  previous_purchases      3900 non-null   int64
 15  payment_method          3900 non-null   object
 16  frequency_of_purchases  3900 non-null   object
 17  age_group               3900 non-null   category
dtypes: category(1), float64(1), int64(4), object(12)
memory usage: 522.1+ KB

In [21]:
#Checking Duplicate.
df.drop_duplicates(subset = ['customer_id'] ,keep = 'first' ,inplace = True)
df[df.duplicated()].shape

(0, 18)

In [22]:
#Checking for inconsistent formating.
for col in df.columns:
    if df[col].nunique() <20:
        print(df[col].value_counts())
        print("-"*50)

gender
Male      2652
Female    1248
Name: count, dtype: int64
--------------------------------------------------
category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64
--------------------------------------------------
size
M     1755
L     1053
S      663
XL     429
Name: count, dtype: int64
--------------------------------------------------
season
Spring    999
Fall      975
Winter    971
Summer    955
Name: count, dtype: int64
--------------------------------------------------
subscription_status
No     2847
Yes    1053
Name: count, dtype: int64
--------------------------------------------------
shipping_type
Free Shipping     675
Standard          654
Store Pickup      650
Next Day Air      648
Express           646
2-Day Shipping    627
Name: count, dtype: int64
--------------------------------------------------
discount_applied
No     2223
Yes    1677
Name: count, dtype: int64
--------------------------------------------------
payment_method
PayPal           677
Credit Card      671
Cash             670
Debit Card       636
Venmo            634
Bank Transfer    612
Name: count, dtype: int64
--------------------------------------------------
frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64
--------------------------------------------------
age_group
Young_Adult    1028
Middle_aged     986
Senior          944
Adult           942
Name: count, dtype: int64
--------------------------------------------------

In [23]:
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly': 7,
    'Annually' : 365,
    'Quarterly' : 90,
    'Every 3 Months' : 90,
    'Bi-Weekly' : 14,
    'Monthly' : 30
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [25]:
#installing dependencies
!pip install mysql-connector-python sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\harsh\appdata\roaming\python\python313\site-packages (9.6.0)
Requirement already satisfied: sqlalchemy in e:\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in e:\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [ ]:
# Connecting to mysql 
from sqlalchemy import create_engine
import urllib.parse
username = "root"
password = "hrt@7480"
safe_password = urllib.parse.quote_plus(password)
port = "3306"
host = "localhost"
database = "customer_behavior"

#Creating engine.
engine = create_engine(f"mysql+mysqlconnector://{username}:{safe_password}@{host}:{port}/{database}")

#Load dataframe into my sql.
table_name = "customer"
df.to_sql(table_name ,engine ,if_exists = "replace",index = False)
print(f"Data successfully loaded to table '{table_name}' in database '{database}'.")

NameError: name 'customer_behavior' is not defined